### ISSUE TITLE
Question about sensitive data

### ISSUE THREAD

**Issue by DanyC97** [wcannon/saltconf2015#6]
Hi @wcannon 

Very impressive work, thx for sharing!!
Now i do see you are using s3 for storing the ssh keys for minions etc, how about pillar secrets?

Say you want/ have some passwords which needs to target various minions? Would you use same s3 bucket or s'thing else?

**Comment by wcannon** [comment]
Thanks.  Glad you like it.

The recommended method for distributing secrets is pillar.  There are issues with this (of course).  Using an S3 bucket would certainly work.  Or you could use a github repo (and encrypt the secrets before putting in github + putting the key in S3 or cloudformation template).
